[package]
name = "bleach-injector"
version = "0.1.0"
authors = ["Rein van der Woerd <reinvanderwoerd@me.com>"]

[dependencies]
vst = "^0.2"
lerp = "0.2.0"
libmath = "0.2.1"
vst-gui = {git = "https://github.com/mikesoylu/rust-vst-gui"}

[lib]
crate-type = ["dylib"]